<?php

use Drupal\Core\Mail\MailManagerInterface;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;

/**
* Implements hook_mail().
*/
function candidates_mail($key, &$message, $params) {
    $options = array(
        'langcode' => $message['langcode'],
    );
    switch ($key) {
        case 'candidates_mail':
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            $message['headers']['MIME-Version'] = '1.0';
            $message['from'] = \Drupal::config('system.site')->get('mail');
            $message['subject'] = $params['title'];
            $message['body'][] = $params['message'];
            break;
    }
}

/**
* Implements hook_theme().
*/
function candidates_theme($existing, $type, $theme, $path) {
    $element['candidate_list'] = [
        'variables' => [
            'candidates' => [],
            'title' => ''
        ],
    ];
    $element['node__candidate'] = [
        'template' => 'node--candidate',
        'base hook' => 'node',
    ];
    return $element;
}

function candidates_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
    if(in_array('node__candidate', $suggestions)){
        $suggestions[] = 'candidate';
    }
}

/**
* Implements hook_form_alter().
*/
function candidates_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    if(in_array($form_id, ['node_candidate_form'])) {
        $form['field_passport_number']['#states'] = [
            'visible' => [
                ':input[name="field_passport"]' => ['value' => 'yes'],
            ],
        ];
    }
    if(in_array($form_id, ['node_candidate_edit_form'])) {
        $form['field_passport_number']['#states'] = [
            'visible' => [
                ':input[name="field_passport"]' => ['value' => 'yes'],
            ],
        ];
    }
}