<?php

use Drupal\Core\Url;
use Drupal\taxonomy\Entity\Term;
use Drupal\Component\Serialization\Json;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Component\Utility\Html;
use Drupal\user\Entity\User;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;

/**
* Implements hook_cron().
*/
function pushnotification_cron() {
    // Service Call
    $config = \Drupal::config('imaservices.settings');
    $start_date = strtotime($config->get('imaservices.reenroll_start_date'));
    $end_date = strtotime($config->get('imaservices.reenroll_end_date'));
    $notification_day = $config->get('imaservices.reenroll_notification_day');
    // Send Re-Enroll push notification once a week (Sunday)
    $present_date = strtotime(date('d-m-Y'));

    if(($start_date <= $present_date) && ($present_date <= $end_date) && (date('l') == $notification_day)) {
        $user_list = \Drupal::database()->query("SELECT `uid` FROM `users_field_data` WHERE `status` = 1")->fetchAll();
        foreach($user_list as $user_ids) {
            $user = User::load($user_ids->uid);
            $role = $user->get('roles')->getValue();
            $user_role = $role[0]['target_id'];
            // Fetch Re-Enrollment status
            $reenroll_status = $user->get('field_reenroll_status')->value;
            $config = \Drupal::config('imaservices.settings');
            $enrollment_year = $config->get('imaservices.msa_enrollment_year');
            $year = $enrollment_year + 1;
            // Fetch user's device tokens
            $notification_tokens = $user->field_notification_token->getString();

            if($reenroll_status != 'YES' && $notification_tokens != '' && $user_role == 'merchant') {
                $user_name = $user->get('field_first_name')->value.' '.$user->get('field_last_name')->value;
                $notify_token_array = explode(', ', $notification_tokens);

                // Sending Re-Enroll Push Notification
                foreach($notify_token_array as $notification_token) {
                    $msg_title = 'IMA Re-Enollment';
                    $msg_body = 'Dear '.$user_name.', please Re-Enroll your IMA account for '.$year;
                    $send_notification = \Drupal::service('pushnotification_service')->send_push_notification($msg_title, $msg_body, $notification_token);
                    $message = 'Re-Enroll notification sent to '.$user_name.' for '.$year.' on '.date('d-m-y');
                    \Drupal::logger('push_notification')->notice($message);
                }
            }
        }
    }
	drupal_flush_all_caches();
}