<?php

/**
 * @file
 * Provide methods to connect with Firebase API.
 */

/**
 * Implements hook_help().
 */
function firebase_help($route_name) {
  switch ($route_name) {
    case 'help.page.firebase':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Firebase module allows you to easly call Firebase APIs to send individual or group messages to mobile devices. This allows you to send push notifications to your users. For more information read the README.md and the online <a href=":field_help" target="docs_firebase">Firebase documentation</a>.', [':field_help' => 'https://firebase.google.com/docs']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dl>';
      $output .= '<dd>' . t('Send push and silent push notifications') . '</dd>';
      $output .= '<dd>' . t('Send group messages') . '</dd>';
      $output .= '<dd>' . t('Customize icon, sound and click action') . '</dd>';
      $output .= '<dd>' . t('Manage topics') . '</dd>';
      $output .= '</dl>';

      return $output;
  }

  return NULL;
}
